services:
  web:
    build: 
      context: .
      dockerfile: docker/prod/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - PHP_ERROR_REPORTING="E_ALL & ~E_DEPRECATED & ~E_STRICT"
      - PHP_DISPLAY_ERRORS=Off
      - PHP_LOG_ERRORS=On
      - MYSQL_USER=${MYSQL_USER:-cubes5_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-cubes5_password}
    networks:
      - cubes5_prod_network

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_prod_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-strong_root_password}
      MYSQL_DATABASE: cubes5_db
      MYSQL_USER: ${MYSQL_USER:-cubes5_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cubes5_password}
    networks:
      - cubes5_prod_network

volumes:
  mysql_prod_data:
    driver: local

networks:
  cubes5_prod_network:
    driver: bridge
