services:
  web:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      - PHP_ERROR_REPORTING=E_ALL
    networks:
      - cubes5_network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cubes5_db
      MYSQL_USER: cubes5_user
      MYSQL_PASSWORD: cubes5_password
    networks:
      - cubes5_network

volumes:
  mysql_data:

networks:
  cubes5_network:
    driver: bridge
